apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: peloton_metrics
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/postgres_root_pw
            - name: POSTGRES_USER_FILE
              value: /secrets/postgres_user
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - name: app-secrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: app-secrets
          secret:
            secretName: app-secrets