{
 "title": "Scoreboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "label": "Year",
    "query": "select DISTINCT TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') FROM public.workouts order by 1 desc;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Workouts",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(w.workout_id) as WorkoutCount\n  ,u.username AS UserName\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nWHERE TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\nGROUP BY 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Cycling Output",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select\n    AVG(avg_output) as avg_output,\n    u.username\nfrom public.workouts w\ninner join public.tracked_users u on u.user_id = w.user_id\ninner join public.workout_performance_metrics m on m.workout_id = w.workout_id\nwhere fitness_discipline IN ('cycling' , 'bike_bootcamp')\n and TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\nGROUP BY 2\norder by 1\n;"
    }
   ]
  },
  {
   "title": "Cycling Miles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT\n  u.username as UserName,\n  SUM(m.total_distance) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline IN ('cycling', 'bike_bootcamp') and m.total_distance is not NULL and distance_unit = 'mi'\nand TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\nGROUP BY 1\norder by 2\n;"
    }
   ]
  },
  {
   "title": "Walking Miles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT\n  u.username as UserName,\n  SUM(m.total_distance) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline IN ('walking') and m.total_distance is not NULL and distance_unit = 'mi'\nand TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\nGROUP BY 1\norder by 2\n;"
    }
   ]
  },
  {
   "title": "Running Miles",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "targets": [
    {
     "rawSql": "SELECT\n  u.username as UserName,\n  SUM(m.total_distance) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline IN ('running') and m.total_distance is not NULL and distance_unit = 'mi'\nand TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\nGROUP BY 1\norder by 2\n;"
    }
   ]
  }
 ]
}