{
 "title": "User Drilldown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "User",
    "query": "SELECT\nusername\nFROM public.tracked_users;"
   },
   {
    "name": "year",
    "label": "Year",
    "query": "select DISTINCT TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') FROM public.workouts\norder by 1 desc;"
   }
  ]
 },
 "panels": [
  {
   "title": "Minutes Exercised ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nCOALESCE(SUM(m.duration/60), 0) \nFROM public.workouts w\nINNER JOIN public.workout_performance_metrics m on m.workout_id = w.workout_id\nINNER JOIN public.tracked_users u on u.user_id = w.user_id\nwhere u.username = '${username}' AND TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\n;"
    }
   ]
  },
  {
   "title": "Time Spent Exercising per Discipline ",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\nw.fitness_discipline,\n SUM(m.duration/60)\n  \nFROM public.workouts w\nINNER JOIN public.workout_performance_metrics m on m.workout_id = w.workout_id\nINNER JOIN public.tracked_users u on u.user_id = w.user_id\nwhere u.username = '${username}' AND TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\ngroup by fitness_discipline\n;"
    }
   ]
  },
  {
   "title": "Miles Cycled",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM(m.total_distance),0) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline IN ('cycling','bike_bootcamp') and m.total_distance is not NULL and distance_unit = 'mi'\nand  username = '${username}' and TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\n;"
    }
   ]
  },
  {
   "title": "The Annual Challenge - Workout Minutes Per Day Needed ",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH minute_goals as (\n    select minute_goal\n  from (\n      values (20000), (18000), (15000), (10000), (9000), (8000), (7000), (6000), (5000), (4000), (3000), (2000), (1000)\n  ) s(minute_goal)\n),\nminutes_exercised as (\n  SELECT\n    COALESCE(SUM(m.duration/60) , 0) as MinutesExercised\n  FROM public.workouts w\n  INNER JOIN public.workout_performance_metrics m on m.workout_id = w.workout_id\n  INNER JOIN public.tracked_users u on u.user_id = w.user_id\n  where u.username = '${username}' and TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\n),\nminutes_needed as (\n    SELECT\n    (minute_goal - MinutesExercised) /  (365 -(current_date - date_trunc('year', now())::date + 1)) as WorkoutMinutesNeededPerDay,\n    minute_goal AS Goal\n  FROM minutes_exercised\n  INNER join minute_goals on 1=1\n  ORDER BY minute_goal desc\n)\nSELECT\nGoal,\nCASE WHEN WorkoutMinutesNeededPerDay < 0 THEN 0 ELSE WorkoutMinutesNeededPerDay END as WorkoutMinutesNeededPerDay\nfrom minutes_needed\n;"
    }
   ]
  },
  {
   "title": "Miles Walked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM(m.total_distance), 0) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline = 'walking' and m.total_distance is not NULL and distance_unit = 'mi'\nand  username = '${username}' and TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\n;"
    }
   ]
  },
  {
   "title": "Workout Minutes Per Year",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(m.duration/60) as TotalWorkoutMinutes,\n  TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY') as \"year\"\nFROM public.workouts w\nINNER JOIN public.workout_performance_metrics m on m.workout_id = w.workout_id\nINNER JOIN public.tracked_users u on u.user_id = w.user_id\nwhere u.username = '${username}'\ngroup by 2\norder by 2\n;"
    }
   ]
  },
  {
   "title": "Miles Ran",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(SUM(m.total_distance),0) as TotalDistance\nFROM workouts w\nINNER JOIN tracked_users u on u.user_id = w.user_id\nINNER JOIN workout_performance_metrics m on m.workout_id = w.workout_id \nwhere fitness_discipline = 'running' and m.total_distance is not NULL and distance_unit = 'mi'\nand  username = '${username}' and TO_CHAR((created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\n;"
    }
   ]
  },
  {
   "title": "Workout Minutes Per Day",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(m.duration/60) as TotalWorkoutMinutes,\n  TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY/MM/DD') as \"date\"\nFROM public.workouts w\nINNER JOIN public.workout_performance_metrics m on m.workout_id = w.workout_id\nINNER JOIN public.tracked_users u on u.user_id = w.user_id\nwhere u.username = '${username}' and TO_CHAR((w.created_at AT TIME ZONE timezone)::date, 'YYYY') = '${year}'\ngroup by 2\n;"
    }
   ]
  }
 ]
}